### ISSUE TITLE
✅ Create tests for `brain_extraction` nodeblock

### ISSUE THREAD

**Issue by shnizzedy** [childmindresearch/nodeblock-testing#2]
### Description

The [`brain_extraction` node block has this decorator](https://github.com/FCP-INDI/C-PAC/blob/6448fed9d4b78029fd86a82fb9942f105cd2b563/CPAC/anat_preproc/anat_preproc.py#L1974-L1993C5):

```Python
@nodeblock(
    name="brain_extraction",
    switch=[
        ["anatomical_preproc", "brain_extraction", "run"],
        ["anatomical_preproc", "run"],
    ],
    inputs=[
        (
            "desc-head_T1w",
            "desc-preproc_T1w",
            ["space-T1w_desc-brain_mask", "space-T1w_desc-acpcbrain_mask"],
        )
    ],
    outputs={
        "desc-preproc_T1w": {"SkullStripped": "True"},
        "desc-brain_T1w": {"SkullStripped": "True"},
        "desc-head_T1w": {"SkullStripped": "False"},
    },
)
def brain_extraction(wf, cfg, strat_pool, pipe_num, opt=None):
```

### Tasks

- [ ] pre-build and package resource pools for the [power set](https://en.wikipedia.org/wiki/Power_set) of `{"desc-head_T1w", "desc-preproc_T1w", "space-T1w_desc-brain_mask", "space-T1w_desc-acpcbrain_mask"}`
- [ ] write tests for connecting
   - [ ] too few resources
   - [ ] minimum sets of resources (`{"desc-head_T1w", "desc-preproc_T1w", "space-T1w_desc-brain_mask"}` and `{"desc-head_T1w", "desc-preproc_T1w", "space-T1w_desc-acpcbrain_mask"}`)
   - [ ] more resources than necessary (full set)
- [ ] write tests for running
